## Librairies and Data Import

In [1]:
import numpy as np  #numpy==1.21.1
import pandas as pd  #pandas==1.3.1

import plotly.graph_objects as go  #plotly==5.3.1
from plotly.subplots import make_subplots  #plotly==5.3.1

from sklearn.linear_model import LinearRegression  #scikit-learn==0.24.2

from functions import color_corr, extract_initial_list_value

In [2]:
df = pd.read_csv("./sim_data.csv")
df.head(20)

,Sample index,Time,Init_Cond_1,Init_Cond_2,Dyn_Input_1,Dyn_Input_2,Dyn_Output_1
0,0,0.0001,0.498024,0.501976,2.564260e-23,0.225052,0.454159
1,0,0.1001,0.498024,0.501976,4.264079e-03,0.116445,0.570981
2,0,0.2001,0.498024,0.501976,9.476366e-03,0.060386,0.570923
3,0,0.3001,0.498024,0.501976,1.468923e-02,0.031298,0.570860
4,0,0.4001,0.498024,0.501976,1.990267e-02,0.016217,0.570794
5,0,0.5001,0.498024,0.501976,2.511671e-02,0.008402,0.570726
6,0,0.6001,0.498024,0.501976,3.033133e-02,0.004354,0.570657
7,0,0.7001,0.498024,0.501976,3.554654e-02,0.002256,0.570588
8,0,0.8001,0.498024,0.501976,4.076235e-02,0.001169,0.570518
9,0,0.9001,0.498024,0.501976,4.597875e-02,0.000607,0.570449
10,0,1.0001,0.498024,0.501976,5.119573e-02,0.000315,0.570379
11,0,1.1001,0.498024,0.501976,5.641331e-02,0.000163,0.570310
12,0,1.2001,0.498024,0.501976,6.163149e-02,0.000085,0.570240
13,0,1.3001,0.498024,0.501976,6.685025e-02,0.000045,0.570171
14,0,1.4001,0.498024,0.501976,7.206961e-02,0.000023,0.570101
15,0,1.5001,0.498024,0.501976,7.728956e-02,0.000012,0.570032
16,0,1.6001,0.498024,0.501976,8.251010e-02,0.000007,0.569962
17,0,1.7001,0.498024,0.501976,8.773123e-02,0.000004,0.569892
18,0,1.8001,0.498024,0.501976,9.295295e-02,0.000002,0.569823
19,0,1.9001,0.498024,0.501976,9.817527e-02,0.000001,0.569753

## Data Exploration

In [ ]:
unique_init_conditions = df[["Init_Cond_1", "Init_Cond_2"]].drop_duplicates()

fig = go.Figure()

fig.add_trace(go.Scatter(x=unique_init_conditions["Init_Cond_1"],
                         y=unique_init_conditions["Init_Cond_2"],
                         mode='markers'))

fig.update_layout(autosize=False, width=600, height=600,
                  title={'text': "Initial conditions spread", 'x': 0.5},
                  xaxis_title="Init_Cond_1",
                  yaxis_title="Init_Cond_2",)

fig.show()

### Series grouped by Initial Conditions

In [4]:
features_list = ["Dyn_Input_1", "Dyn_Input_2", "Dyn_Output_1"]

df_series = pd.DataFrame(columns=features_list)

for feature in features_list:

    df_series[feature] = df.groupby(["Init_Cond_1", "Init_Cond_2"])[feature].apply(list)

df_series = df_series.reset_index()
df_series.sample(10)

,Init_Cond_1,Init_Cond_2,Dyn_Input_1,Dyn_Input_2,Dyn_Output_1
146,0.731225,0.047431,"[2.481541837659083e-23, 0.0084061475284747, 0....","[0.6600047514209653, 0.1982961967324976, 0.058...","[0.0460158029803763, 0.1118923506897272, 0.111..."
199,1.000000,0.000000,"[2.481541837659083e-23, 0.0089411950689045, 0....","[1.0, 0.2809455259022885, 0.0777419277076127, ...","[0.0, 0.0596812791122951, 0.0596567158922577, ..."
92,0.458498,0.968379,"[2.481541837659083e-23, 0.001162052193153, 0.0...","[0.1367933055567359, 0.105597096643099, 0.0832...","[0.821248734888486, 0.9759735011507183, 0.9758..."
187,0.936759,0.948617,"[2.3161057151484772e-23, 0.0012754739177, 0.00...","[0.2788372341036295, 0.2122580421677389, 0.164...","[0.8061012879421956, 0.959662555236662, 0.9595..."
196,0.984190,0.806324,"[0.0, 0.0021307978464507, 0.0051107451652158, ...","[0.3271541987972176, 0.223234007254709, 0.1541...","[0.6984575611012365, 0.8420015250391408, 0.841..."
129,0.644269,0.071146,"[2.3988237764037806e-23, 0.0081486588232567, 0...","[0.554272829566631, 0.1721293908241001, 0.0529...","[0.0687549720249625, 0.1376591731225461, 0.137..."
43,0.209486,0.790514,"[2.5642598989143858e-23, 0.0022253202013258, 0...","[0.0743275875163202, 0.0500247074582557, 0.034...","[0.687021199621697, 0.829409493956266, 0.82932..."
139,0.695652,0.478261,"[2.481541837659083e-23, 0.0044497503595027, 0....","[0.3199844750352575, 0.1617423814049793, 0.081...","[0.4340323585285708, 0.5485164925240136, 0.548..."
181,0.905138,0.474308,"[2.481541837659083e-23, 0.0044822351940857, 0....","[0.4156899542960208, 0.2094237120948593, 0.105...","[0.4305239786368253, 0.5446019224058491, 0.544..."
180,0.901186,0.525692,"[2.481541837659083e-23, 0.0040855639735082, 0....","[0.3909584460028047, 0.2073689932142931, 0.110...","[0.4736553636443746, 0.5927338049707693, 0.592..."

### Graphic representation of some sampled batches

In [ ]:
df_series_sample = df_series.sample(20)

for dyn_variable in df_series_sample.columns[2:5]:

    fig = go.Figure()

    for values in df_series_sample[dyn_variable]:

        fig.add_trace(go.Scatter(y=values, mode='lines'))

    fig.update_layout(autosize=False, width=600, height=600,
                      showlegend=False,
                      title={'text': dyn_variable, 'x': 0.5},
                      xaxis_title="Time")

    fig.update_xaxes(range=[-5, 105])

    fig.show()

### Dyn_Input_1 Features Extraction

In [6]:
# We create a Numpy Array corresponding to the time elapsed
X_Time = np.sort(df["Time"].unique()).reshape(-1, 1)

reg_dyn_input_1 = LinearRegression(fit_intercept=False)

# We iterate on each row (series) of the DataFrame to fit a linear regression
# and extract the corresponding coefficients and score
for idx in df_series.index:

    # We create a Numpy Array corresponding to the time elapsed
    y_dyn_input_1 = np.array(df_series["Dyn_Input_1"].loc[idx])
    reg_dyn_input_1.fit(X_Time, y_dyn_input_1)

    df_series.loc[idx, "reg_dyn_input_1_coef"] = reg_dyn_input_1.coef_
    df_series.loc[idx, "reg_dyn_input_1_score"] = reg_dyn_input_1.score(X_Time, y_dyn_input_1)

df_series[[
    'Init_Cond_1',
    'Init_Cond_2',
    'Dyn_Input_1',
    'reg_dyn_input_1_coef',
    'reg_dyn_input_1_score',
    ]]

,Init_Cond_1,Init_Cond_2,Dyn_Input_1,reg_dyn_input_1_coef,reg_dyn_input_1_score
0,0.000000,0.667984,"[2.481541837659083e-23, 0.0030439327122523, 0....",0.039531,0.999962
1,0.003953,0.332016,"[2.481541837659083e-23, 0.0056467529135914, 0....",0.066365,0.999987
2,0.007905,0.802372,"[2.5642598989143858e-23, 0.002147679314619, 0....",0.030097,0.999932
3,0.011858,0.197628,"[2.481541837659083e-23, 0.0068669389750197, 0....",0.078820,0.999991
4,0.015810,0.399209,"[2.3988237764037806e-23, 0.0050799148433895, 0...",0.060561,0.999985
...,...,...,...,...,...
195,0.980237,0.193676,"[2.481541837659083e-23, 0.0069103243330955, 0....",0.079267,0.999991
196,0.984190,0.806324,"[0.0, 0.0021307978464507, 0.0051107451652158, ...",0.029916,0.999928
197,0.988142,0.328063,"[2.481541837659083e-23, 0.005687294649416, 0.0...",0.066784,0.999987
198,0.996047,1.000000,"[2.3988237764037806e-23, 0.0009986338676791, 0...",0.017491,0.999798
199,1.000000,0.000000,"[2.481541837659083e-23, 0.0089411950689045, 0....",0.099913,0.999995

In [7]:
print(f"Mean of reg_dyn_input_1_score: {df_series['reg_dyn_input_1_score'].mean():.5f}\n")

df_series_corr1 = df_series[["Init_Cond_1", "Init_Cond_2", "reg_dyn_input_1_coef"]].corr()

df_series_corr1[["Init_Cond_1", "Init_Cond_2"]].iloc[2:, :].style.applymap(color_corr)

Mean of reg_dyn_input_1_score: 0.99996

### Dyn_Input_2 Features Extraction

#### Example of one root transformation

In [8]:
# We define the root ratio used to convert the curved section into a linear one
ROOT_RATIO = 50
THRESHOLD = 0.00003

In [ ]:
# Initial curve
y_dyn_input_2 = np.array(df_series["Dyn_Input_2"].loc[2])

# We spot the curve limit
y_dyn_input_2_limit = np.argmax(y_dyn_input_2 < THRESHOLD)

# We root the curve section to get a linear profile
y_dyn_input_2_root = y_dyn_input_2[0:y_dyn_input_2_limit]**(1/ROOT_RATIO)

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(go.Scatter(y=y_dyn_input_2[0:y_dyn_input_2_limit], mode='lines+markers', name='original'), secondary_y=False)
fig.add_trace(go.Scatter(y=y_dyn_input_2_root[0:y_dyn_input_2_limit], mode='lines+markers', name='root^'+str(ROOT_RATIO)), secondary_y=True)

fig.update_layout(autosize=False, width=600, height=600,
                  showlegend=True,
                  title={'text': 'Dyn_Input_2', 'x': 0.5},
                  xaxis_title="Time")

fig.show()

#### Root transformation and linear regression of all batches

In [10]:
reg_dyn_input_2 = LinearRegression()

# We iterate on each row (series) of the DataFrame to fit a linear regression
# and extract the corresponding coefficients and score
for idx in df_series.index:

    y_dyn_input_2 = np.array(df_series["Dyn_Input_2"].loc[idx])

    # We spot the curve limit
    y_dyn_input_2_root_limit = np.argmax(y_dyn_input_2 < THRESHOLD)

    # We root the curve section to get a linear profile
    y_dyn_input_2_root = y_dyn_input_2[0:y_dyn_input_2_root_limit]**(1/ROOT_RATIO)

    # We create a linear regression to get corresponding coefficients
    reg_dyn_input_2.fit(X_Time[0:y_dyn_input_2_root_limit], y_dyn_input_2_root)

    df_series.loc[idx, "reg_dyn_input_2_coef"] = reg_dyn_input_2.coef_
    df_series.loc[idx, "reg_dyn_input_2_inter"] = reg_dyn_input_2.intercept_
    df_series.loc[idx, "y_dyn_input_2_root_limit"] = y_dyn_input_2_root_limit
    df_series.loc[idx, "reg_dyn_input_2_score"] = reg_dyn_input_2.score(X_Time[0:y_dyn_input_2_root_limit], y_dyn_input_2_root)

df_series[[
    'Init_Cond_1',
    'Init_Cond_2',
    'Dyn_Input_2',
    'reg_dyn_input_2_coef',
    'reg_dyn_input_2_inter',
    'reg_dyn_input_2_score',
    ]]

,Init_Cond_1,Init_Cond_2,Dyn_Input_2,reg_dyn_input_2_coef,reg_dyn_input_2_inter,reg_dyn_input_2_score
0,0.000000,0.667984,"[0.0049136809270093, 0.0035060147218375, 0.002...",-0.083757,0.900483,0.999566
1,0.003953,0.332016,"[0.0093122558396249, 0.0043473415865428, 0.001...",-0.144663,0.910903,0.999891
2,0.007905,0.802372,"[0.0069508151388086, 0.0049591947454177, 0.003...",-0.064310,0.905217,0.999875
3,0.011858,0.197628,"[0.0166734073555905, 0.0062285573625797, 0.002...",-0.173584,0.920613,0.999631
4,0.015810,0.399209,"[0.0144003909055995, 0.0067505150909448, 0.003...",-0.132840,0.917914,0.999778
...,...,...,...,...,...,...
195,0.980237,0.193676,"[0.6614007631383336, 0.2426502643827574, 0.088...",-0.183055,0.989585,0.999303
196,0.984190,0.806324,"[0.3271541987972176, 0.223234007254709, 0.1541...",-0.066283,0.975241,0.999343
197,0.988142,0.328063,"[0.543756938554163, 0.2342030731210375, 0.1005...",-0.152287,0.985465,0.999230
198,0.996047,1.000000,"[0.2852910716845356, 0.2251169763559635, 0.181...",-0.038486,0.972617,0.999480
199,1.000000,0.000000,"[1.0, 0.2809455259022885, 0.0777419277076127, ...",-0.231432,0.997235,0.999050

In [11]:
print(f"Mean of reg_dyn_input_2_score: {df_series['reg_dyn_input_2_score'].mean():.5f}")
print(f"Location of the y_root_limit: Min({df_series['y_dyn_input_2_root_limit'].min():.0f}) - \
Median({df_series['y_dyn_input_2_root_limit'].median():.0f}) - \
Max({df_series['y_dyn_input_2_root_limit'].max():.0f})\n")

df_series_corr2 = df_series[["Init_Cond_1",
                             "Init_Cond_2",
                             "reg_dyn_input_1_coef",
                             "reg_dyn_input_2_coef",
                             "reg_dyn_input_2_inter"]].corr()

df_series_corr2[["Init_Cond_1", "Init_Cond_2"]].iloc[2:, :].style.applymap(color_corr)

Mean of reg_dyn_input_2_score: 0.99940
Location of the y_root_limit: Min(7) - Median(14) - Max(43)

### Dyn_Output_1 Features Extraction

In [12]:
reg_dyn_output_1 = LinearRegression()

# We iterate on each row (series) of the DataFrame to fit a linear regression
# and extract the corresponding coefficients and score
for idx in df_series.index:

    # We extract the initial state of dyn_output_1
    df_series["dyn_output_1_initial"] = df_series.apply(lambda row: extract_initial_list_value(row["Dyn_Output_1"]), axis=1)

    y_dyn_output_1 = np.array(df_series["Dyn_Output_1"].loc[idx][1:])

    # We create a linear regression to get corresponding coefficients
    reg_dyn_output_1 = LinearRegression().fit(X_Time[1:], y_dyn_output_1)

    df_series.loc[idx, "reg_dyn_output_1_coef"] = reg_dyn_output_1.coef_
    df_series.loc[idx, "reg_dyn_output_1_inter"] = reg_dyn_output_1.intercept_
    df_series.loc[idx, "reg_dyn_output_1_score"] = reg_dyn_output_1.score(X_Time[1:], y_dyn_output_1)

df_series[[
    'Init_Cond_1',
    'Init_Cond_2',
    'Dyn_Output_1',
    'dyn_output_1_initial',
    'reg_dyn_output_1_coef',
    'reg_dyn_output_1_inter',
    'reg_dyn_output_1_score'
    ]]

,Init_Cond_1,Init_Cond_2,Dyn_Output_1,dyn_output_1_initial,reg_dyn_output_1_coef,reg_dyn_output_1_inter,reg_dyn_output_1_score
0,0.000000,0.667984,"[0.590702987463432, 0.7228860340027474, 0.7228...",0.590703,-0.000673,0.722715,0.997072
1,0.003953,0.332016,"[0.3083332425305907, 0.4077732901250869, 0.407...",0.308333,-0.000465,0.407624,0.997246
2,0.007905,0.802372,"[0.6963913271417335, 0.8397382558584656, 0.839...",0.696391,-0.000772,0.839603,0.997558
3,0.011858,0.197628,"[0.187425851910914, 0.2717582257724748, 0.2717...",0.187426,-0.000385,0.271632,0.997433
4,0.015810,0.399209,"[0.3670003652926158, 0.4735440771286306, 0.473...",0.367000,-0.000507,0.473386,0.997126
...,...,...,...,...,...,...,...
195,0.980237,0.193676,"[0.1832262228305504, 0.2670462003444336, 0.267...",0.183226,-0.000396,0.266947,0.997181
196,0.984190,0.806324,"[0.6984575611012365, 0.8420015250391408, 0.841...",0.698458,-0.000810,0.842008,0.998612
197,0.988142,0.328063,"[0.3041634770181456, 0.4031146930127692, 0.403...",0.304163,-0.000482,0.403008,0.997118
198,0.996047,1.000000,"[0.8438958578275415, 1.0, 0.9999229704347432, ...",0.843896,-0.000952,1.000143,0.999892
199,1.000000,0.000000,"[0.0, 0.0596812791122951, 0.0596567158922577, ...",0.000000,-0.000270,0.059606,0.997458

In [13]:
print(f"Mean of reg_dyn_onput_1_score: {df_series['reg_dyn_output_1_score'].mean():.5f}\n")

df_series_corr3 = df_series[["Init_Cond_1",
                             "Init_Cond_2",
                             "dyn_output_1_initial",
                             "reg_dyn_output_1_coef",
                             "reg_dyn_output_1_inter"]].corr()

df_series_corr3[["Init_Cond_1", "Init_Cond_2"]].iloc[2:, :].style.applymap(color_corr)

Mean of reg_dyn_onput_1_score: 0.99770

### Overall correlation of Dynamic variables with initial conditions

#### Overall correlation

In [14]:
df_series_corr4 = df_series[["Init_Cond_1",
                             "Init_Cond_2",
                             "reg_dyn_input_1_coef",
                             "reg_dyn_input_2_coef",
                             "reg_dyn_input_2_inter",
                             "dyn_output_1_initial",
                             "reg_dyn_output_1_coef",
                             "reg_dyn_output_1_inter"]].corr()

df_series_corr4[["Init_Cond_1", "Init_Cond_2"]].iloc[2:, :].style.applymap(color_corr)

#### Model(s) building

In [15]:
df_series_to_model = df_series.drop(["Dyn_Input_1",
                                     "Dyn_Input_2",
                                     "Dyn_Output_1",
                                     "reg_dyn_input_1_score",
                                     "y_dyn_input_2_root_limit",
                                     "reg_dyn_input_2_score",
                                     "reg_dyn_output_1_score"], axis=1)
df_series_to_model

,Init_Cond_1,Init_Cond_2,reg_dyn_input_1_coef,reg_dyn_input_2_coef,reg_dyn_input_2_inter,dyn_output_1_initial,reg_dyn_output_1_coef,reg_dyn_output_1_inter
0,0.000000,0.667984,0.039531,-0.083757,0.900483,0.590703,-0.000673,0.722715
1,0.003953,0.332016,0.066365,-0.144663,0.910903,0.308333,-0.000465,0.407624
2,0.007905,0.802372,0.030097,-0.064310,0.905217,0.696391,-0.000772,0.839603
3,0.011858,0.197628,0.078820,-0.173584,0.920613,0.187426,-0.000385,0.271632
4,0.015810,0.399209,0.060561,-0.132840,0.917914,0.367000,-0.000507,0.473386
...,...,...,...,...,...,...,...,...
195,0.980237,0.193676,0.079267,-0.183055,0.989585,0.183226,-0.000396,0.266947
196,0.984190,0.806324,0.029916,-0.066283,0.975241,0.698458,-0.000810,0.842008
197,0.988142,0.328063,0.066784,-0.152287,0.985465,0.304163,-0.000482,0.403008
198,0.996047,1.000000,0.017491,-0.038486,0.972617,0.843896,-0.000952,1.000143
199,1.000000,0.000000,0.099913,-0.231432,0.997235,0.000000,-0.000270,0.059606

In [16]:
X_init = df_series_to_model[["Init_Cond_1", "Init_Cond_2"]]

y_list = ["reg_dyn_input_1_coef", "reg_dyn_input_2_coef", "reg_dyn_input_2_inter", "dyn_output_1_initial", "reg_dyn_output_1_coef", "reg_dyn_output_1_inter"]

models_coef = pd.DataFrame(index=y_list, columns=["init_cond_1_coef_", "init_cond_2_coef_", "intercept_", "score"])

for y_name in y_list:
    y = df_series_to_model[y_name]
    model = LinearRegression().fit(X_init, y)
    
    models_coef.loc[y_name, "init_cond_1_coef_"] = model.coef_[0]
    models_coef.loc[y_name, "init_cond_2_coef_"] = model.coef_[1]
    models_coef.loc[y_name, "intercept_"] = model.intercept_
    models_coef.loc[y_name, "score"] = model.score(X_init, y)

models_coef

,init_cond_1_coef_,init_cond_2_coef_,intercept_,score
reg_dyn_input_1_coef,0.000296,-0.081193,0.094822,0.993613
reg_dyn_input_2_coef,-0.003907,0.189187,-0.215242,0.990767
reg_dyn_input_2_inter,0.052176,-0.023429,0.950314,0.847258
dyn_output_1_initial,-0.001748,0.842061,0.022228,0.998616
reg_dyn_output_1_coef,-0.000016,-0.000675,-0.000251,0.998354
reg_dyn_output_1_inter,-0.002019,0.939389,0.087542,0.998201

#### Class Creation

In [17]:
class SurrogatePrediction:

    def __init__(self, ic1, ic2, models_coef, root_ratio=50):

        if all(isinstance(i, (int, float)) for i in [ic1, ic2, root_ratio]):
            self.ic1 = ic1
            self.ic2 = ic2
            self.root_ratio = root_ratio
            self.X_sim = np.round(np.linspace(0.0001, 10, 101), 5)
            print("Initial conditions recorded!")
        else:
            print("Check arguments' types!")

    def __str__(self):
        description = "This surrogate prediction is based on IC1: " \
                    + str(round(self.ic1, 4)) + " and IC2: " + str(round(self.ic2, 4)) \
                    + " with a 1/" + str(self.root_ratio) + " root ratio."
        return description

    def dyn_input_1(self):

        dyn_input_1_coef = (self.ic1 * models_coef.loc["reg_dyn_input_1_coef", "init_cond_1_coef_"])
        dyn_input_1_coef += (self.ic2 * models_coef.loc["reg_dyn_input_1_coef", "init_cond_2_coef_"])
        dyn_input_1_coef += models_coef.loc["reg_dyn_input_1_coef", "intercept_"]

        dyn_input_1_series = dyn_input_1_coef * self.X_sim
        
        return dyn_input_1_series

    def dyn_input_2(self):

        dyn_input_2_coef = (self.ic1 * models_coef.loc["reg_dyn_input_2_coef", "init_cond_1_coef_"])
        dyn_input_2_coef += (self.ic2 * models_coef.loc["reg_dyn_input_2_coef", "init_cond_2_coef_"])
        dyn_input_2_coef += models_coef.loc["reg_dyn_input_2_coef", "intercept_"]

        dyn_input_2_inter = (self.ic1 * models_coef.loc["reg_dyn_input_2_inter", "init_cond_1_coef_"])
        dyn_input_2_inter += (self.ic2 * models_coef.loc["reg_dyn_input_2_inter", "init_cond_2_coef_"])
        dyn_input_2_inter += models_coef.loc["reg_dyn_input_2_inter", "intercept_"]

        dyn_input_2_series = (dyn_input_2_coef * self.X_sim + dyn_input_2_inter)**self.root_ratio
        
        return dyn_input_2_series

    def dyn_output_1(self):

        # Define the initial position [0] of the time-series
        dyn_output_1_initial = (self.ic1 * models_coef.loc["dyn_output_1_initial", "init_cond_1_coef_"])
        dyn_output_1_initial += (self.ic2 * models_coef.loc["dyn_output_1_initial", "init_cond_2_coef_"])
        dyn_output_1_initial += models_coef.loc["dyn_output_1_initial", "intercept_"]
        
        # Define the time-series after initial position
        reg_dyn_output_1_coef = (self.ic1 * models_coef.loc["reg_dyn_output_1_coef", "init_cond_1_coef_"])
        reg_dyn_output_1_coef += (self.ic2 * models_coef.loc["reg_dyn_output_1_coef", "init_cond_2_coef_"])
        reg_dyn_output_1_coef += models_coef.loc["reg_dyn_output_1_coef", "intercept_"]

        reg_dyn_output_1_inter = (self.ic1 * models_coef.loc["reg_dyn_output_1_inter", "init_cond_1_coef_"])
        reg_dyn_output_1_inter += (self.ic2 * models_coef.loc["reg_dyn_output_1_inter", "init_cond_2_coef_"])
        reg_dyn_output_1_inter += models_coef.loc["reg_dyn_output_1_inter", "intercept_"]

        dyn_input_3_series_after_0 = reg_dyn_output_1_coef * self.X_sim[1:] + reg_dyn_output_1_inter

        return np.concatenate((np.array([dyn_output_1_initial]), dyn_input_3_series_after_0))

In [18]:
idx = 20
ic1 = df_series["Init_Cond_1"].iloc[idx]
ic2 = df_series["Init_Cond_2"].iloc[idx]

surr_pred = SurrogatePrediction(ic1=ic1, ic2=ic2, models_coef=models_coef)
print(surr_pred)
print()
print("surr_pred.dyn_input_1()")
print(surr_pred.dyn_input_1())
print()
print("surr_pred.dyn_input_2()")
print(surr_pred.dyn_input_2())
print()
print("surr_pred.dyn_output_1()")
print(surr_pred.dyn_output_1())

Initial conditions recorded!
This surrogate prediction is based on IC1: 0.0988 and IC2: 0.1739 with a 1/50 root ratio.

surr_pred.dyn_input_1()
[8.07305814e-06 8.08113120e-03 1.61541893e-02 2.42272475e-02
 3.23003056e-02 4.03733638e-02 4.84456146e-02 5.65186727e-02
 6.45917309e-02 7.26647890e-02 8.07378472e-02 8.88109053e-02
 9.68839634e-02 1.04957022e-01 1.13030080e-01 1.21102331e-01
 1.29175389e-01 1.37248447e-01 1.45321505e-01 1.53394563e-01
 1.61467621e-01 1.69540679e-01 1.77613738e-01 1.85686796e-01
 1.93759854e-01 2.01832912e-01 2.09905163e-01 2.17978221e-01
 2.26051279e-01 2.34124337e-01 2.42197395e-01 2.50270454e-01
 2.58343512e-01 2.66416570e-01 2.74489628e-01 2.82561879e-01
 2.90634937e-01 2.98707995e-01 3.06781053e-01 3.14854111e-01
 3.22927169e-01 3.31000228e-01 3.39073286e-01 3.47146344e-01
 3.55219402e-01 3.63291653e-01 3.71364711e-01 3.79437769e-01
 3.87510827e-01 3.95583885e-01 4.03656944e-01 4.11730002e-01
 4.19803060e-01 4.27876118e-01 4.35949176e-01 4.44021427e-01
 4.52094485e-01 4.60167543e-01 4.68240601e-01 4.76313660e-01
 4.84386718e-01 4.92459776e-01 5.00532834e-01 5.08605892e-01
 5.16678950e-01 5.24752008e-01 5.32824259e-01 5.40897317e-01
 5.48970376e-01 5.57043434e-01 5.65116492e-01 5.73189550e-01
 5.81262608e-01 5.89335666e-01 5.97408724e-01 6.05480975e-01
 6.13554033e-01 6.21627091e-01 6.29700150e-01 6.37773208e-01
 6.45846266e-01 6.53919324e-01 6.61992382e-01 6.70065440e-01
 6.78138498e-01 6.86211557e-01 6.94283807e-01 7.02356866e-01
 7.10429924e-01 7.18502982e-01 7.26576040e-01 7.34649098e-01
 7.42722156e-01 7.50795214e-01 7.58868273e-01 7.66940523e-01
 7.75013582e-01 7.83086640e-01 7.91159698e-01 7.99232756e-01
 8.07305814e-01]

surr_pred.dyn_input_2()
[8.27251485e-002 3.13702042e-002 1.16699350e-002 4.25554053e-003
 1.51991521e-003 5.31230443e-004 1.81546896e-004 6.05917285e-005
 1.97307341e-005 6.26163157e-006 1.93428517e-006 5.80869583e-007
 1.69338863e-007 4.78523579e-008 1.30863009e-008 3.45778518e-009
 8.80868371e-010 2.15935324e-010 5.08240832e-011 1.14576542e-011
 2.46747212e-012 5.06150831e-013 9.85816187e-014 1.81667398e-014
 3.15529408e-015 5.14301695e-016 7.83100027e-017 1.10752391e-017
 1.44644165e-018 1.73270244e-019 1.88927415e-020 1.85876042e-021
 1.63367426e-022 1.26797515e-023 8.57508693e-025 4.97576981e-026
 2.43040120e-027 9.77702724e-029 3.15399378e-030 7.89746430e-032
 1.47417804e-033 1.94962605e-035 1.71121764e-037 9.14733587e-040
 2.65144182e-042 3.54519515e-045 1.72280366e-048 2.11151287e-052
 3.54837779e-057 2.63516873e-063 7.07585637e-072 3.04914657e-086
 1.47545628e-146 3.98238940e-089 2.56655024e-073 2.88388320e-064
 6.75244759e-058 5.59962974e-053 5.70010936e-049 1.37377084e-045
 1.15742814e-042 4.37831714e-040 8.81694008e-038 1.06695360e-035
 8.48324380e-034 4.74199150e-032 1.96336840e-030 6.28162559e-029
 1.60528398e-027 3.36767396e-026 5.93262637e-025 8.94416855e-024
 1.17266340e-022 1.35546466e-021 1.39763343e-020 1.29843154e-019
 1.09702648e-018 8.49322691e-018 6.06695505e-017 4.02306641e-016
 2.48993756e-015 1.44534744e-014 7.90317156e-014 4.08678750e-013
 2.00566064e-012 9.37190882e-012 4.18123551e-011 1.78640800e-010
 7.32580430e-010 2.89005426e-009 1.09908619e-008 4.03702485e-008
 1.43469898e-007 4.94127247e-007 1.65178327e-006 5.36616600e-006
 1.69684868e-005 5.22839977e-005 1.57158025e-004 4.61328056e-004
 1.32380133e-003]

surr_pred.dyn_output_1()
[0.16850067 0.2506777  0.25064071 0.25060372 0.25056673 0.25052974
 0.25049275 0.25045576 0.25041877 0.25038178 0.25034479 0.2503078
 0.25027081 0.25023382 0.25019684 0.25015985 0.25012286 0.25008587
 0.25004888 0.25001189 0.2499749  0.24993791 0.24990092 0.24986393
 0.24982694 0.24978995 0.24975297 0.24971598 0.24967899 0.249642
 0.24960501 0.24956802 0.24953103 0.24949404 0.24945705 0.24942007
 0.24938308 0.24934609 0.2493091  0.24927211 0.24923512 0.24919813
 0.24916114 0.24912415 0.24908716 0.24905017 0.24901319 0.2489762
 0.24893921 0.24890222 0.24886523 0.24882824 0.24879125 0.24875426
 0.24871727 0.24868028 0.24864329 0.2486063  0.24856931 0.24853232
 0.24849534 0.24845835 0.24842136 0.24838437 0.24834738 0.24831039
 0.2482734  0.24823641 0.24819942 0.24816243 0.24812544 0.24808845
 0.24805146 0.24801448 0.24797749 0.2479405  0.24790351 0.24786652
 0.24782953 0.24779254 0.24775555 0.24771856 0.24768157 0.24764458
 0.24760759 0.2475706  0.24753362 0.24749663 0.24745964 0.24742265
 0.24738566 0.24734867 0.24731168 0.24727469 0.2472377  0.24720072
 0.24716373 0.24712674 0.24708975 0.24705276 0.24701577]

#### Visual comparison of predictions and ground truth

In [ ]:
idx = 20
ic1 = df_series["Init_Cond_1"].iloc[idx]
ic2 = df_series["Init_Cond_2"].iloc[idx]

surr_pred = SurrogatePrediction(ic1=ic1, ic2=ic2, models_coef=models_coef)
print(surr_pred, "\n")

var_to_predict_list = ["Dyn_Input_1", "Dyn_Input_2", "Dyn_Output_1"]
predictions = [surr_pred.dyn_input_1(), surr_pred.dyn_input_2(), surr_pred.dyn_output_1()]
x_range_limits = [100, 40, 100]
start_y_plot_list = [-0.1, -0.01, -0.01]

for var_to_predict, prediction, x_range_limit, start_y_plot in zip(var_to_predict_list, predictions, x_range_limits, start_y_plot_list):

    fig = go.Figure()

    fig.add_trace(go.Scatter(y=prediction[:x_range_limit], mode='markers', name='predicted', marker=dict(size=4)))
    fig.add_trace(go.Scatter(y=df_series[var_to_predict].iloc[idx][:x_range_limit], mode='lines', name='truth (y)'))

    fig.update_layout(autosize=False, width=600, height=600, title=var_to_predict, title_x=0.5)

    fig.update_yaxes(range=[start_y_plot, max(max(prediction), max(df_series[var_to_predict].iloc[idx]))*1.1])
    
    fig.show()